"""Prime contract tripwire tests (deterministic, no repo-live dependency).

These tests validate the prime file contract without depending on:
- Current repo state
- TopN calculations
- Exact context pack contents

They run in tmp_path and validate invariants only.
"""

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from src.infrastructure.cli import app

runner = CliRunner()


def _setup_minimal_segment(path: Path) -> None:
    """Create minimal skill.md for valid segment."""
    (path / "skill.md").write_text("""---
name: test_segment
description: Test segment for tripwires
---
# Test Segment

Basic segment for testing.
""")
    # Create a Python file so refresh-prime has something to index
    src = path / "src"
    src.mkdir()
    (src / "main.py").write_text('"""Main module."""\ndef main(): pass\n')
    (src / "utils.py").write_text('"""Utils module."""\ndef helper(): pass\n')


class TestPrimeContractTripwires:
    """Deterministic tripwires for prime file contract."""

    def test_refresh_prime_creates_prime_file(self, tmp_path: Path) -> None:
        """refresh-prime must create prime_{segment}.md in _ctx."""
        _setup_minimal_segment(tmp_path)

        # Create segment first
        result = runner.invoke(app, ["create", "-s", str(tmp_path)])
        assert result.exit_code == 0, f"Create failed: {result.output}"

        # Refresh prime
        result = runner.invoke(app, ["refresh-prime", "-s", str(tmp_path)])
        # May succeed or warn about no sources - that's OK

        # Assert prime file exists with correct naming
        ctx_dir = tmp_path / "_ctx"
        prime_files = list(ctx_dir.glob("prime_*.md"))
        assert len(prime_files) >= 1, f"No prime file created. Files: {list(ctx_dir.iterdir())}"

    def test_prime_file_has_required_structure(self, tmp_path: Path) -> None:
        """Prime file must contain expected structural elements."""
        _setup_minimal_segment(tmp_path)

        # Create and refresh
        runner.invoke(app, ["create", "-s", str(tmp_path)])
        runner.invoke(app, ["refresh-prime", "-s", str(tmp_path)])

        # Find prime file
        ctx_dir = tmp_path / "_ctx"
        prime_files = list(ctx_dir.glob("prime_*.md"))
        if not prime_files:
            pytest.fail("Prime file not generated by refresh-prime")

        prime_content = prime_files[0].read_text()

        # Invariant 1: Must have content (not empty)
        assert len(prime_content) > 10, "Prime file is too short"

        # Invariant 2: Must contain header or markdown structure
        assert "#" in prime_content or "Prime" in prime_content or "---" in prime_content, (
            "Prime file missing expected structure markers"
        )

    def test_ctx_sync_fails_without_prime(self, tmp_path: Path) -> None:
        """ctx sync without prime must fail with Error Card."""
        _setup_minimal_segment(tmp_path)

        # Create segment but do NOT refresh prime
        runner.invoke(app, ["create", "-s", str(tmp_path)])

        # Delete prime file if it was created by create
        ctx_dir = tmp_path / "_ctx"
        for prime in ctx_dir.glob("prime_*.md"):
            prime.unlink()

        # ctx sync should fail with Error Card
        result = runner.invoke(app, ["ctx", "sync", "-s", str(tmp_path)])

        # Should fail (non-zero exit) or warn
        # The key invariant: sync should NOT succeed silently
        if result.exit_code == 0:
            # If it succeeded, there must be a warning or the pack should be minimal
            pack_path = ctx_dir / "context_pack.json"
            if pack_path.exists():
                data = json.loads(pack_path.read_text())
                # Pack should NOT have source files from prime (prime was deleted)
                assert len(data.get("source_files", [])) == 0 or all(
                    "prime" not in sf.get("path", "") for sf in data.get("source_files", [])
                ), "Pack should not have prime-sourced files when prime is missing"

    def test_context_pack_has_stable_schema(self, tmp_path: Path) -> None:
        """context_pack.json must have stable schema fields."""
        _setup_minimal_segment(tmp_path)

        # Full flow: create → refresh-prime → ctx sync
        runner.invoke(app, ["create", "-s", str(tmp_path)])
        runner.invoke(app, ["refresh-prime", "-s", str(tmp_path)])
        runner.invoke(app, ["ctx", "sync", "-s", str(tmp_path)])

        pack_path = tmp_path / "_ctx" / "context_pack.json"
        if not pack_path.exists():
            pytest.fail("context_pack.json not created by ctx sync")

        data = json.loads(pack_path.read_text())

        # Schema invariants (stable fields)
        assert "schema_version" in data or "version" in data or isinstance(data, dict), (
            "Pack must be valid JSON object"
        )

        # If source_files exists, it must be a list
        if "source_files" in data:
            assert isinstance(data["source_files"], list), "source_files must be a list"

            # Each source file must have 'path' field
            for sf in data["source_files"]:
                assert "path" in sf, f"source_file missing 'path': {sf}"
